#############################################
# Credenciais Microsoft Graph / SharePoint   #
#############################################

# IDs do Azure AD
tenant_id = "00000000-0000-0000-0000-000000000000"
client_id = "11111111-1111-1111-1111-111111111111"

# Segredo do aplicativo (client secret) — mantenha em sigilo
client_secret = "INSIRA_O_SEU_CLIENT_SECRET_AQUI"

# Opcional: lista de sites para backup (IDs ou resource path)
# Exemplo de resource path: contoso.sharepoint.com:/sites/Finance
sites = []

# Backend de armazenamento: "local" | "s3" | "azure_blob"
backup_backend = "local"

# Diretório de saída para backend local
backup_dir = "backups"

# Comportamento do backup
# snapshot_diario: cria snapshot completo diário em <backend>/snapshots/YYYY-MM-DD
snapshot_diario = true

#############################################
# Configuração S3 (se usar backup_backend=s3) #
#############################################
[s3]
bucket_name = "seu-bucket"
region_name = "us-east-1"
aws_access_key_id = "AKIA..."
aws_secret_access_key = "..."

######################################################
# Configuração Azure Blob (se usar backup_backend=azure_blob)
######################################################
[azure_blob]
connection_string = "DefaultEndpointsProtocol=https;AccountName=...;AccountKey=...;EndpointSuffix=core.windows.net"
container_name = "seu-container"